# Generated by Django 4.1.3 on 2022-11-06 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Choices",
            new_name="Choice",
        ),
    ]
